# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: da286740397765f20141b2d5ecd999432943c743b14cb91409b064ca5fcce99c69a6bece24438c8ae915bf626e9bf7cba296b7e5da02960255e18076fd3af1e2

test:
  secret_key_base: ffd24b24fe5621be4fcd25ffb1fe330b1048b0259553ede05fd5ccd3bfbbc785531a14ee2f011d2c6253fed2d148e994a605a5d541f3f73f0a4cc415801c323c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
